//-------------------------------------------------------------------------
// Xor2_noparam.v
//-------------------------------------------------------------------------
// This file is generated by PyMTL SystemVerilog translation pass.

// PyMTL Component Xor2 Definition
// At /home/vboxuser/Desktop/CSE293-Final-Project/Lab1/Part1/xor2/xor2.py

module Xor2_noparam
(
  input  logic [0:0] a_i ,
  input  logic [0:0] b_i ,
  output logic [0:0] c_o ,
  input  logic [0:0] clk ,
  input  logic [0:0] reset 
);

  // PyMTL Update Block Source
  // At /home/vboxuser/Desktop/CSE293-Final-Project/Lab1/Part1/xor2/xor2.py:20
  // @update
  // def xorblk():
  //   # YOUR CODE START
  //   s.c_o @= s.a_i ^ s.b_i
  //   # YOUR CODE END
  
  always_comb begin : xorblk
    c_o = a_i ^ b_i;
  end

endmodule
