//-------------------------------------------------------------------------
// Counter__nbits_22.v
//-------------------------------------------------------------------------
// This file is generated by PyMTL SystemVerilog translation pass.

// PyMTL Component Counter Definition
// At /home/vboxuser/Desktop/CSE293-Final-Project/Lab1/Part2/counter/counter.py

module Counter__nbits_22
(
  input  logic [0:0] clk ,
  output logic [21:0] count_o ,
  input  logic [0:0] down_i ,
  input  logic [0:0] reset ,
  input  logic [0:0] up_i 
);
  logic [21:0] next_w;

  // PyMTL Update Block Source
  // At /home/vboxuser/Desktop/CSE293-Final-Project/Lab1/Part2/counter/counter.py:31
  // @update
  // # YOUR CODE HERE
  // def updateblk():
  //     s.count_o @= s.next_w
  
  always_comb begin : updateblk
    count_o = next_w;
  end

  // PyMTL Update Block Source
  // At /home/vboxuser/Desktop/CSE293-Final-Project/Lab1/Part2/counter/counter.py:20
  // @update_ff
  // # YOUR CODE HERE
  // # Use <<= for sequential assignment
  // def countblk():
  //   if (s.up_i & ~s.down_i):
  //     #print("Entered")
  //     #print("count: "+ str(s.count_o))
  //     s.next_w <<= s.count_o + 1
  //   elif (~s.up_i & s.down_i):
  //     s.next_w <<= s.count_o - 1
  
  always_ff @(posedge clk) begin : countblk
    if ( up_i & ( ~down_i ) ) begin
      next_w <= count_o + 22'd1;
    end
    else if ( ( ~up_i ) & down_i ) begin
      next_w <= count_o - 22'd1;
    end
  end

endmodule
